2019-12-20 15:40:02.623 [error] <0.405.0>@gen_server:init_it:366 CRASH REPORT Process <0.405.0> with 0 neighbours exited with reason: bad return value: #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>},pid => <0.419.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>}} in gen_server:init_it/6 line 366
2019-12-20 15:51:36.486 [error] <0.405.0>@Elixir.QueueWorker:init:13 CRASH REPORT Process <0.405.0> with 0 neighbours crashed with reason: no match of right hand value {error,{{invalid_vhost,"/khatabook"},"amqp://kbadmin:s78hfycz31qohxes@localhost:5672//khatabook"}} in 'Elixir.QueueWorker':init/1 line 13
2019-12-20 15:52:35.550 [error] <0.405.0>@Elixir.QueueWorker:init:13 CRASH REPORT Process <0.405.0> with 0 neighbours crashed with reason: no match of right hand value {error,{{invalid_entitiy,['%',50,107]},"amqp://kbadmin:s78hfycz31qohxes@localhost:5672/%2khatabook"}} in 'Elixir.QueueWorker':init/1 line 13
2019-12-20 15:52:58.265 [error] <0.405.0>@gen_server:init_it:366 CRASH REPORT Process <0.405.0> with 0 neighbours exited with reason: bad return value: #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>},pid => <0.419.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>}} in gen_server:init_it/6 line 366
2019-12-20 16:07:08.632 [error] <0.405.0>@gen_server:init_it:366 CRASH REPORT Process <0.405.0> with 0 neighbours exited with reason: bad return value: #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>},pid => <0.419.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>}} in gen_server:init_it/6 line 366
2019-12-20 16:10:26.896 [error] <0.405.0>@gen_server:init_it:366 CRASH REPORT Process <0.405.0> with 0 neighbours exited with reason: bad return value: #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>},pid => <0.419.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.408.0>}} in gen_server:init_it/6 line 366
2019-12-20 16:35:24.001 [error] <0.436.0> 'Elixir.QueueConsumer' <0.436.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-75uLPcRy6gH0a3Ws8pR6Wg">>}}
2019-12-20 16:47:04.484 [error] <0.299.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueuePool' started with 'Elixir.QueuePool':start_link([{pool_size,2}]) at undefined exit with reason {'EXIT',{function_clause,[{'Elixir.GenServer',start_link,['Elixir.QueuePool',<0.403.0>,'Elixir.QueuePool'],[{file,"lib/gen_server.ex"},{line,901}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{...},...]}} in context start_error
2019-12-20 16:49:07.484 [error] <0.421.0> gen_server <0.421.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.421.0> but no handle_call/3 clause was provided">>} in 'Elixir.QueueWorker':handle_call/3 line 774
2019-12-20 16:49:07.503 [error] <0.421.0> CRASH REPORT Process <0.421.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.421.0> but no handle_call/3 clause was provided">>} in 'Elixir.QueueWorker':handle_call/3 line 774
2019-12-20 16:49:07.504 [error] <0.404.0> Supervisor {<0.404.0>,poolboy_sup} had child 'Elixir.QueueWorker' started with {'Elixir.QueueWorker',start_link,undefined} at <0.421.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.421.0> but no handle_call/3 clause was provided">>} in 'Elixir.QueueWorker':handle_call/3 line 774 in context child_terminated
2019-12-20 16:49:07.504 [error] <0.435.0> gen_server 'Elixir.QueuePool' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.421.0> but no handle_call/3 clause was provided">>},[{'Elixir.QueueWorker',handle_call,3,[{file,"lib/gen_server.ex"},{line,774}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[<0.421.0>,{msg,<<"Hey">>},5000]}} in 'Elixir.GenServer':call/3 line 1010
2019-12-20 16:49:07.509 [error] <0.435.0> CRASH REPORT Process 'Elixir.QueuePool' with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.421.0> but no handle_call/3 clause was provided">>},[{'Elixir.QueueWorker',handle_call,3,[{file,"lib/gen_server.ex"},{line,774}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[<0.421.0>,{msg,<<"Hey">>},5000]}} in 'Elixir.GenServer':call/3 line 1010
2019-12-20 16:49:07.510 [error] <0.299.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueuePool' started with 'Elixir.QueuePool':start_link([{pool_size,2}]) at <0.435.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.421.0> but no handle_call/3 clause was provided">>},[{'Elixir.QueueWorker',handle_call,3,[{file,"lib/gen_server.ex"},{line,774}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[<0.421.0>,{msg,<<"Hey">>},5000]}} in context child_terminated
2019-12-20 16:49:30.609 [error] <0.412.0> gen_server <0.412.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.412.0> but no handle_call/3 clause was provided">>} in 'Elixir.QueueWorker':handle_call/3 line 774
2019-12-20 16:49:30.616 [error] <0.412.0> CRASH REPORT Process <0.412.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.412.0> but no handle_call/3 clause was provided">>} in 'Elixir.QueueWorker':handle_call/3 line 774
2019-12-20 16:49:30.616 [error] <0.395.0> Supervisor {<0.395.0>,poolboy_sup} had child 'Elixir.QueueWorker' started with {'Elixir.QueueWorker',start_link,undefined} at <0.412.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.412.0> but no handle_call/3 clause was provided">>} in 'Elixir.QueueWorker':handle_call/3 line 774 in context child_terminated
2019-12-20 16:49:30.616 [error] <0.426.0> gen_server 'Elixir.QueuePool' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.412.0> but no handle_call/3 clause was provided">>},[{'Elixir.QueueWorker',handle_call,3,[{file,"lib/gen_server.ex"},{line,774}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[<0.412.0>,{msg,<<"Hey">>},5000]}} in 'Elixir.GenServer':call/3 line 1010
2019-12-20 16:49:30.619 [error] <0.426.0> CRASH REPORT Process 'Elixir.QueuePool' with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.412.0> but no handle_call/3 clause was provided">>},[{'Elixir.QueueWorker',handle_call,3,[{file,"lib/gen_server.ex"},{line,774}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[<0.412.0>,{msg,<<"Hey">>},5000]}} in 'Elixir.GenServer':call/3 line 1010
2019-12-20 16:49:30.620 [error] <0.290.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueuePool' started with 'Elixir.QueuePool':start_link([{pool_size,2}]) at <0.426.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.412.0> but no handle_call/3 clause was provided">>},[{'Elixir.QueueWorker',handle_call,3,[{file,"lib/gen_server.ex"},{line,774}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[<0.412.0>,{msg,<<"Hey">>},5000]}} in context child_terminated
2019-12-20 16:50:42.880 [error] <0.435.0>@Elixir.IO:puts:649 gen_server 'Elixir.QueuePool' terminated with reason: no case clause matching {<<"got message">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 16:50:42.890 [error] <0.435.0>@Elixir.IO:puts:649 CRASH REPORT Process 'Elixir.QueuePool' with 0 neighbours crashed with reason: no case clause matching {<<"got message">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 16:50:42.890 [error] <0.299.0>@Elixir.IO:puts:649 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueuePool' started with 'Elixir.QueuePool':start_link([{pool_size,2}]) at <0.435.0> exit with reason no case clause matching {<<"got message">>} in 'Elixir.IO':puts/2 line 649 in context child_terminated
2019-12-20 16:52:01.609 [error] <0.440.0> gen_server 'Elixir.QueuePool' terminated with reason: bad return value: {no_reply,<0.408.0>}
2019-12-20 16:52:01.609 [error] <0.440.0>@gen_server:handle_common_reply:755 CRASH REPORT Process 'Elixir.QueuePool' with 0 neighbours exited with reason: bad return value: {no_reply,<0.408.0>} in gen_server:handle_common_reply/8 line 755
2019-12-20 16:52:01.609 [error] <0.304.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueuePool' started with 'Elixir.QueuePool':start_link([{pool_size,2}]) at <0.440.0> exit with reason bad return value: {no_reply,<0.408.0>} in context child_terminated
2019-12-20 16:52:01.617 [error] <0.426.0> gen_server <0.426.0> terminated with reason: bad return value: {no_reply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.429.0>},pid => <0.438.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.429.0>}}}
2019-12-20 16:52:01.619 [error] <0.426.0>@gen_server:handle_common_reply:755 CRASH REPORT Process <0.426.0> with 0 neighbours exited with reason: bad return value: {no_reply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.429.0>},pid => <0.438.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.429.0>}}} in gen_server:handle_common_reply/8 line 755
2019-12-20 16:52:01.620 [error] <0.409.0> Supervisor {<0.409.0>,poolboy_sup} had child 'Elixir.QueueWorker' started with {'Elixir.QueueWorker',start_link,undefined} at <0.426.0> exit with reason bad return value: {no_reply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.429.0>},pid => <0.438.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.429.0>}}} in context child_terminated
2019-12-20 16:57:05.776 [error] <0.435.0> gen_server 'Elixir.QueuePool' terminated with reason: bad return value: {no_reply,<0.403.0>}
2019-12-20 16:57:05.782 [error] <0.421.0> gen_server <0.421.0> terminated with reason: bad return value: {no_reply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.424.0>},pid => <0.433.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.424.0>}}}
2019-12-20 16:57:05.791 [error] <0.435.0>@gen_server:handle_common_reply:755 CRASH REPORT Process 'Elixir.QueuePool' with 0 neighbours exited with reason: bad return value: {no_reply,<0.403.0>} in gen_server:handle_common_reply/8 line 755
2019-12-20 16:57:05.791 [error] <0.299.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueuePool' started with 'Elixir.QueuePool':start_link([{pool_size,2}]) at <0.435.0> exit with reason bad return value: {no_reply,<0.403.0>} in context child_terminated
2019-12-20 16:57:05.796 [error] <0.421.0>@gen_server:handle_common_reply:755 CRASH REPORT Process <0.421.0> with 0 neighbours exited with reason: bad return value: {no_reply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.424.0>},pid => <0.433.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.424.0>}}} in gen_server:handle_common_reply/8 line 755
2019-12-20 16:57:05.796 [error] <0.404.0> Supervisor {<0.404.0>,poolboy_sup} had child 'Elixir.QueueWorker' started with {'Elixir.QueueWorker',start_link,undefined} at <0.421.0> exit with reason bad return value: {no_reply,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.424.0>},pid => <0.433.0>},connection => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.424.0>}}} in context child_terminated
2019-12-20 16:59:41.870 [error] <0.436.0>@Elixir.IO:inspect:399 gen_server <0.436.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-3j2SXJtjLQPOQVc16p0yJQ">>}}) line 399
2019-12-20 16:59:41.893 [error] <0.436.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.436.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-3j2SXJtjLQPOQVc16p0yJQ">>}}) line 399
2019-12-20 16:59:41.893 [error] <0.299.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.436.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-3j2SXJtjLQPOQVc16p0yJQ">>}}) line 399 in context child_terminated
2019-12-20 16:59:41.910 [error] <0.453.0>@Elixir.IO:inspect:399 gen_server <0.453.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-fy5MM6TOo4-BWQbOy9BPZg">>}}) line 399
2019-12-20 16:59:41.910 [error] <0.453.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.453.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-fy5MM6TOo4-BWQbOy9BPZg">>}}) line 399
2019-12-20 16:59:41.910 [error] <0.299.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.453.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-fy5MM6TOo4-BWQbOy9BPZg">>}}) line 399 in context child_terminated
2019-12-20 16:59:41.926 [error] <0.468.0>@Elixir.IO:inspect:399 gen_server <0.468.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-NSxzHQqS02VBcoPfZXV7iA">>}}) line 399
2019-12-20 16:59:41.927 [error] <0.468.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.468.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-NSxzHQqS02VBcoPfZXV7iA">>}}) line 399
2019-12-20 16:59:41.927 [error] <0.299.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.468.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-NSxzHQqS02VBcoPfZXV7iA">>}}) line 399 in context child_terminated
2019-12-20 16:59:41.943 [error] <0.483.0>@Elixir.IO:inspect:399 gen_server <0.483.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-pvKXaG6pP4AB0eGghTjVew">>}}) line 399
2019-12-20 16:59:41.944 [error] <0.483.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.483.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-pvKXaG6pP4AB0eGghTjVew">>}}) line 399
2019-12-20 16:59:41.944 [error] <0.299.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.483.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-pvKXaG6pP4AB0eGghTjVew">>}}) line 399 in context child_terminated
2019-12-20 16:59:41.944 [error] <0.299.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.483.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 17:03:01.002 [error] <0.443.0> gen_server <0.443.0> terminated with reason: {socket_error,timeout}
2019-12-20 17:03:01.002 [error] <0.428.0> gen_server <0.428.0> terminated with reason: {socket_error,timeout}
2019-12-20 17:03:01.003 [error] <0.424.0> gen_server <0.424.0> terminated with reason: {socket_error,timeout}
2019-12-20 17:03:01.003 [error] <0.439.0> gen_server <0.439.0> terminated with reason: {socket_error,timeout}
2019-12-20 17:03:01.003 [error] <0.439.0> CRASH REPORT Process <0.439.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 17:03:01.003 [error] <0.424.0> CRASH REPORT Process <0.424.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 17:03:01.004 [error] <0.422.0> Supervisor {<0.422.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.423.0>, {amqp_params_network,<<"kbadmin">>,<<"tdHb9RwA9X+NdJzs03wyHKjzHFrrHMcoGq4Pef9EGjQQ6hCxPWj/NYCCS/4C...">>,...}) at <0.424.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 17:03:01.004 [error] <0.422.0> Supervisor {<0.422.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.423.0>, {amqp_params_network,<<"kbadmin">>,<<"tdHb9RwA9X+NdJzs03wyHKjzHFrrHMcoGq4Pef9EGjQQ6hCxPWj/NYCCS/4C...">>,...}) at <0.424.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 17:03:01.004 [error] <0.437.0> Supervisor {<0.437.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.438.0>, {amqp_params_network,<<"kbadmin">>,<<"y1IxFnJZgbpwCgPVb2i5JzkxVOJuIh5nuypL8KKIkZx0JXbMtqblFXFkqihD...">>,...}) at <0.439.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 17:03:01.004 [error] <0.437.0> Supervisor {<0.437.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.438.0>, {amqp_params_network,<<"kbadmin">>,<<"y1IxFnJZgbpwCgPVb2i5JzkxVOJuIh5nuypL8KKIkZx0JXbMtqblFXFkqihD...">>,...}) at <0.439.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 17:03:01.010 [error] <0.414.0> gen_server <0.414.0> terminated with reason: {socket_error,timeout}
2019-12-20 17:03:01.010 [error] <0.408.0> gen_server <0.408.0> terminated with reason: {socket_error,timeout}
2019-12-20 17:03:01.010 [error] <0.408.0> CRASH REPORT Process <0.408.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 17:03:01.011 [error] <0.406.0> Supervisor {<0.406.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.407.0>, {amqp_params_network,<<"kbadmin">>,<<"cSW7/pb+FG0IuA5M5DpkRBZOOqoJTiazWHywQwyNOUMOlfqoAX7XYpTJPQtU...">>,...}) at <0.408.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 17:03:01.011 [error] <0.406.0> Supervisor {<0.406.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.407.0>, {amqp_params_network,<<"kbadmin">>,<<"cSW7/pb+FG0IuA5M5DpkRBZOOqoJTiazWHywQwyNOUMOlfqoAX7XYpTJPQtU...">>,...}) at <0.408.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 17:09:26.524 [error] <0.421.0>@gen_server:call gen_server <0.421.0> terminated with reason: no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-20 17:09:26.540 [error] <0.421.0>@gen_server:call CRASH REPORT Process <0.421.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-20 17:09:26.540 [error] <0.404.0>@gen_server:call Supervisor {<0.404.0>,poolboy_sup} had child 'Elixir.QueueWorker' started with {'Elixir.QueueWorker',start_link,undefined} at <0.421.0> exit with reason no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-20 17:51:27.088 [error] <0.480.0>@rabbit_framing_amqp_0_9_1:shortstr_size:187 CRASH REPORT Process <0.480.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 187
2019-12-20 17:54:57.465 [error] <0.440.0>@Elixir.SmppWorker:init:16 CRASH REPORT Process <0.440.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.SmppWorker':init/1 line 16
2019-12-20 18:00:17.822 [error] <0.440.0>@Elixir.SmppWorker:init:16 CRASH REPORT Process <0.440.0> with 0 neighbours crashed with reason: no match of right hand value {error,timeout} in 'Elixir.SmppWorker':init/1 line 16
2019-12-20 18:46:37.929 [error] <0.443.0>@Elixir.IO:puts:649 gen_server <0.443.0> terminated with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:37.969 [error] <0.443.0>@Elixir.IO:puts:649 CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:37.969 [error] <0.301.0>@Elixir.IO:puts:649 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.443.0> exit with reason no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649 in context child_terminated
2019-12-20 18:46:37.985 [error] <0.460.0>@Elixir.IO:puts:649 gen_server <0.460.0> terminated with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:37.986 [error] <0.460.0>@Elixir.IO:puts:649 CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:37.986 [error] <0.301.0>@Elixir.IO:puts:649 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.460.0> exit with reason no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649 in context child_terminated
2019-12-20 18:46:38.002 [error] <0.475.0>@Elixir.IO:puts:649 gen_server <0.475.0> terminated with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:38.002 [error] <0.475.0>@Elixir.IO:puts:649 CRASH REPORT Process <0.475.0> with 0 neighbours crashed with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:38.002 [error] <0.301.0>@Elixir.IO:puts:649 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.475.0> exit with reason no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649 in context child_terminated
2019-12-20 18:46:38.017 [error] <0.490.0>@Elixir.IO:puts:649 gen_server <0.490.0> terminated with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:38.018 [error] <0.490.0>@Elixir.IO:puts:649 CRASH REPORT Process <0.490.0> with 0 neighbours crashed with reason: no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649
2019-12-20 18:46:38.018 [error] <0.301.0>@Elixir.IO:puts:649 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.490.0> exit with reason no case clause matching {<<"Consumer:">>} in 'Elixir.IO':puts/2 line 649 in context child_terminated
2019-12-20 18:46:38.018 [error] <0.301.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.490.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 18:46:52.415 [error] <0.443.0>@Elixir.IO:inspect:399 gen_server <0.443.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-vsufcFfNvKWoM0nzkUjkWg">>}}) line 399
2019-12-20 18:46:52.438 [error] <0.443.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-vsufcFfNvKWoM0nzkUjkWg">>}}) line 399
2019-12-20 18:46:52.438 [error] <0.301.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.443.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-vsufcFfNvKWoM0nzkUjkWg">>}}) line 399 in context child_terminated
2019-12-20 18:46:52.454 [error] <0.460.0>@Elixir.IO:inspect:399 gen_server <0.460.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-DpPKRNvHU6VOBgbtyVlCOA">>}}) line 399
2019-12-20 18:46:52.454 [error] <0.460.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-DpPKRNvHU6VOBgbtyVlCOA">>}}) line 399
2019-12-20 18:46:52.455 [error] <0.301.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.460.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-DpPKRNvHU6VOBgbtyVlCOA">>}}) line 399 in context child_terminated
2019-12-20 18:46:52.469 [error] <0.475.0>@Elixir.IO:inspect:399 gen_server <0.475.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-lqpgzc-9zRqo3fmgsRyuWQ">>}}) line 399
2019-12-20 18:46:52.470 [error] <0.475.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.475.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-lqpgzc-9zRqo3fmgsRyuWQ">>}}) line 399
2019-12-20 18:46:52.470 [error] <0.301.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.475.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-lqpgzc-9zRqo3fmgsRyuWQ">>}}) line 399 in context child_terminated
2019-12-20 18:46:52.485 [error] <0.490.0>@Elixir.IO:inspect:399 gen_server <0.490.0> terminated with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-SOp0W57CvqJag9SK1e8LCA">>}}) line 399
2019-12-20 18:46:52.485 [error] <0.490.0>@Elixir.IO:inspect:399 CRASH REPORT Process <0.490.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-SOp0W57CvqJag9SK1e8LCA">>}}) line 399
2019-12-20 18:46:52.485 [error] <0.301.0>@Elixir.IO:inspect:399 Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.490.0> exit with reason no function clause matching 'Elixir.IO':inspect(stdio, <<"Consumer:">>, {basic_consume_ok,#{consumer_tag => <<"amq.ctag-SOp0W57CvqJag9SK1e8LCA">>}}) line 399 in context child_terminated
2019-12-20 18:46:52.485 [error] <0.301.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.490.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 18:47:24.723 [error] <0.443.0>@erlang:+ gen_server <0.443.0> terminated with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-vlMETpAbW7D2m_UEmDGzCQ">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.747 [error] <0.443.0>@erlang:+ CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-vlMETpAbW7D2m_UEmDGzCQ">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.747 [error] <0.301.0>@erlang:+ Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.443.0> exit with reason bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-vlMETpAbW7D2m_UEmDGzCQ">>}}, <<"Consumer:">>) in context child_terminated
2019-12-20 18:47:24.763 [error] <0.460.0>@erlang:+ gen_server <0.460.0> terminated with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-AsjjH-E6zeh5afha-IWrwQ">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.764 [error] <0.460.0>@erlang:+ CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-AsjjH-E6zeh5afha-IWrwQ">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.764 [error] <0.301.0>@erlang:+ Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.460.0> exit with reason bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-AsjjH-E6zeh5afha-IWrwQ">>}}, <<"Consumer:">>) in context child_terminated
2019-12-20 18:47:24.781 [error] <0.475.0>@erlang:+ gen_server <0.475.0> terminated with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-mHcCekajIzs2BHyYhVotLg">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.781 [error] <0.475.0>@erlang:+ CRASH REPORT Process <0.475.0> with 0 neighbours crashed with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-mHcCekajIzs2BHyYhVotLg">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.781 [error] <0.301.0>@erlang:+ Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.475.0> exit with reason bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-mHcCekajIzs2BHyYhVotLg">>}}, <<"Consumer:">>) in context child_terminated
2019-12-20 18:47:24.796 [error] <0.490.0>@erlang:+ gen_server <0.490.0> terminated with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-fwbnR_0s3lwixQ-I-tz1eA">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.797 [error] <0.490.0>@erlang:+ CRASH REPORT Process <0.490.0> with 0 neighbours crashed with reason: bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-fwbnR_0s3lwixQ-I-tz1eA">>}}, <<"Consumer:">>)
2019-12-20 18:47:24.797 [error] <0.301.0>@erlang:+ Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.490.0> exit with reason bad arithmetic expression in erlang:'+'({basic_consume_ok,#{consumer_tag => <<"amq.ctag-fwbnR_0s3lwixQ-I-tz1eA">>}}, <<"Consumer:">>) in context child_terminated
2019-12-20 18:47:24.797 [error] <0.301.0> Supervisor 'Elixir.SmsServer.Supervisor' had child 'Elixir.QueueConsumer' started with 'Elixir.QueueConsumer':start_link([]) at <0.490.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 19:06:43.004 [error] <0.435.0> gen_server <0.435.0> terminated with reason: {socket_error,timeout}
2019-12-20 19:06:43.004 [error] <0.446.0> gen_server <0.446.0> terminated with reason: {timers,enquire_link_timer}
2019-12-20 19:06:43.004 [error] <0.455.0> gen_server <0.455.0> terminated with reason: {socket_error,timeout}
2019-12-20 19:06:43.004 [error] <0.451.0> gen_server <0.451.0> terminated with reason: {socket_error,timeout}
2019-12-20 19:06:43.004 [error] <0.431.0> gen_server <0.431.0> terminated with reason: {socket_error,timeout}
2019-12-20 19:06:43.011 [error] <0.421.0> gen_server <0.421.0> terminated with reason: {socket_error,timeout}
2019-12-20 19:06:43.011 [error] <0.415.0> gen_server <0.415.0> terminated with reason: {socket_error,timeout}
2019-12-20 19:06:44.157 [error] <0.435.0> CRASH REPORT Process <0.435.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 19:06:44.158 [error] <0.455.0> CRASH REPORT Process <0.455.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 19:06:44.158 [error] <0.450.0> Supervisor {<0.450.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.34>, <0.451.0>, <0.453.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50589 -> 127.0.0.1:5672">>) at <0.455.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 19:06:44.159 [error] <0.450.0> Supervisor {<0.450.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.34>, <0.451.0>, <0.453.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50589 -> 127.0.0.1:5672">>) at <0.455.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 19:06:44.159 [error] <0.415.0> CRASH REPORT Process <0.415.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 19:06:44.159 [error] <0.431.0> CRASH REPORT Process <0.431.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 19:06:44.159 [error] <0.413.0> Supervisor {<0.413.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.414.0>, {amqp_params_network,<<"kbadmin">>,<<"jmqwp0SqNfJK6Pe0PWTTmtSQpELfv2g4y9wXdh2TeMFqGS5xla34HIGKmS3v...">>,...}) at <0.415.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 19:06:44.159 [error] <0.413.0> Supervisor {<0.413.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.414.0>, {amqp_params_network,<<"kbadmin">>,<<"jmqwp0SqNfJK6Pe0PWTTmtSQpELfv2g4y9wXdh2TeMFqGS5xla34HIGKmS3v...">>,...}) at <0.415.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 19:06:44.159 [error] <0.429.0> Supervisor {<0.429.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.430.0>, {amqp_params_network,<<"kbadmin">>,<<"nQasVubadlD3NMEm5Ad6q7Z3nOi8jVCHM7uj5hZx26t8KPd9ZKL8H8a1sS5I...">>,...}) at <0.431.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 19:06:44.159 [error] <0.429.0> Supervisor {<0.429.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.430.0>, {amqp_params_network,<<"kbadmin">>,<<"nQasVubadlD3NMEm5Ad6q7Z3nOi8jVCHM7uj5hZx26t8KPd9ZKL8H8a1sS5I...">>,...}) at <0.431.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 19:06:44.160 [error] <0.430.0> Supervisor {<0.430.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.32>, <0.431.0>, <0.433.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50587 -> 127.0.0.1:5672">>) at <0.435.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 19:06:44.160 [error] <0.430.0> Supervisor {<0.430.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.32>, <0.431.0>, <0.433.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50587 -> 127.0.0.1:5672">>) at <0.435.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 19:06:44.160 [error] <0.421.0> CRASH REPORT Process <0.421.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 19:06:44.160 [error] <0.451.0> CRASH REPORT Process <0.451.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-20 19:06:44.160 [error] <0.414.0> Supervisor {<0.414.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.31>, <0.415.0>, <0.419.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50586 -> 127.0.0.1:5672">>) at <0.421.0> exit with reason noproc in context shutdown_error
2019-12-20 19:06:44.160 [error] <0.449.0> Supervisor {<0.449.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.450.0>, {amqp_params_network,<<"kbadmin">>,<<"ZOnVEN8Qrn3ZN4ct9/jCn/IuGIqiA7Uz76YO5avBF8Ie26TFwu1nn261W4++...">>,...}) at <0.451.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-20 19:06:44.160 [error] <0.449.0> Supervisor {<0.449.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.450.0>, {amqp_params_network,<<"kbadmin">>,<<"ZOnVEN8Qrn3ZN4ct9/jCn/IuGIqiA7Uz76YO5avBF8Ie26TFwu1nn261W4++...">>,...}) at <0.451.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-20 19:06:44.176 [error] <0.446.0> CRASH REPORT Process <0.446.0> with 1 neighbours exited with reason: {timers,enquire_link_timer} in gen_server:handle_common_reply/8 line 751
2019-12-20 19:06:44.176 [error] <0.444.0> Supervisor {<0.444.0>,poolboy_sup} had child 'Elixir.SmppWorker' started with {'Elixir.SmppWorker',start_link,undefined} at <0.445.0> exit with reason {timers,enquire_link_timer} in context child_terminated
2019-12-20 19:06:44.355 [error] <0.467.0>@Elixir.SmppWorker:init:15 CRASH REPORT Process <0.467.0> with 0 neighbours crashed with reason: no match of right hand value {error,nxdomain} in 'Elixir.SmppWorker':init/1 line 15
2019-12-20 19:06:44.924 [error] <0.443.0>@poolboy:new_worker:283 gen_server <0.443.0> terminated with reason: no match of right hand value {error,{{badmatch,{error,nxdomain}},[{'Elixir.SmppWorker',init,1,[{file,"lib/sms_server/smpp/smpp_worker.ex"},{line,15}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}} in poolboy:new_worker/1 line 283
2019-12-20 19:06:44.925 [error] <0.443.0>@poolboy:new_worker:283 CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: no match of right hand value {error,{{badmatch,{error,nxdomain}},[{'Elixir.SmppWorker',init,1,[{file,"lib/sms_server/smpp/smpp_worker.ex"},{line,15}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}} in poolboy:new_worker/1 line 283
